### PR TITLE
Some fixes for Visual Studio 2013 on Windows 8.1

### PR DESCRIPTION
**Pull request by CallForSanity**
Works perfectly now

### CODE REVIEW

**Comment by matus-chochlik** [comment]
Hi,

Thanks for the updates, for now I've cherry-picked only the first two commits. The `install` instruction for lib oglplus causes cmake to complain. The library is not part of the `all` target and sometimes it may fail to build and currently it's only used by some of the examples. Until that is sorted out I'd prefer not to install it via cmake.

**Comment by matus-chochlik** [comment]
Ok, I've also cherry-picked the fourth commit.

**Comment by CallForSanity** [comment]
Cool, thank you.

oglplus is great by the way.
Keep up the good work!

**Comment by matus-chochlik** [comment]
NP, Thank You!

I'll close this issue and put the thing with installing the lib on the TODO list.

**Pull request closed without merging**
